apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-interswitch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-interswitch
  template:
    metadata:
      labels:
        app: hello-interswitch
    spec:
      containers:
      - name: hello-interswitch
        image: mdhelloacr/hello-interswitch:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hello-interswitch-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-interswitch
