name: CI/CD to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: mdhelloacr.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . -t mdhelloacr.azurecr.io/hello-interswitch:latest
        docker push mdhelloacr.azurecr.io/hello-interswitch:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        inlineScript: az aks get-credentials --resource-group hello-rg --name helloCluster


    - name: AKS Login
      run: az aks get-credentials --resource-group hello-rg --name helloCluster

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yml
